version: '2'

services:
  db:
    image: postgres
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '9090:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=email@email.com
      - PGADMIN_DEFAULT_PASSWORD=password